# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Appyness-dashie"
license = "MIT"
licenselink = "https://github.com/vervallsweg/hugo-appyness-dashie/blob/master/LICENSE"
description = "Appyness is an app showcase theme, you can list all the app features with screenshots using colored slides. It supports all the features required for an app showcase website."
homepage = "https://uicard.io/products/hugo-appyness/"
tags = ["app","showcase","disqus","google analytics","blog","changelog","minimal","responsive"]
features = ["disqus","google analytics", "app showcase"]
min_version = "0.41"

[author]
  name = "vervallsweg"
  repo = "https://github.com/vervallsweg/hugo-appyness-dashie"

[original]
  name = "UICardio"
  homepage = "https://uicard.io"
  repo = "https://github.com/uicardiodev/hugo-appyness"
